Support logging in from Azure IAM
christophgysin/avpnc pull request #2
Opened 2023-01-03 19:48 UTC by agilob

Azure responds to Aviatrix client using OPTIONS, because why not

2023-01-03 21:42 UTC, christophgysin requested changes

2023-01-03 21:42 UTC, christophgysin commented on avpnc
> +        self.extract_response_and_login()
You could just:
```suggestion
        return self.do_POST()
```

2023-01-03 21:42 UTC, christophgysin commented on avpnc
> +        global credentials = json.loads(unquote(self.path[1:]))
Why do you need to `unquote()`? Can you provide a (sanitized) example response?

2023-01-03 21:42 UTC, christophgysin commented on avpnc
> +        openvpn(credentials['Email'], credentials['Token'])
This should not be needed.

2023-01-04 20:19 UTC, christophgysin approved these changes

2023-01-04 20:19 UTC, merged

2023-01-04 20:19 UTC, christophgysin commented
Thanks!

2023-01-05 18:53 UTC, agilob commented
Alright, I see you're the AUR maintainer too, would you mind updating AUR please?

2023-01-05 20:38 UTC, christophgysin commented
Done, thanks for the reminder.